config/routes.rb
Rails.application.routes.draw do
 
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	mount_devise_token_auth_for 'User', at: 'auth'
	
	get '/allegro', to: 'allegro#index'
  # get '/categories', to: 'category#index'
 	resources :barcodes do 
      post :get_barcode, on: :collection
 		resources :results
 	end
  
  resources :barcode_no_logins
  
  get '/scanner', to: 'barcodes#scanner'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barcode.rb
class Barcode < ApplicationRecord
	belongs_to :user
	has_many :results
	validates :code, presence: true
end

app/models/barcode_no_login.rb
class BarcodeNoLogin < ApplicationRecord
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :barcode
end

app/models/user.rb
class User < ApplicationRecord
            # Include default devise modules.
        devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
            include DeviseTokenAuth::Concerns::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
end

app/controllers/allegro_controller.rb
class AllegroController < ApplicationController
  require "uri"
  require "net/http"

  def index
  	uri = URI.parse("https://allegro.pl/auth/oauth/token?grant_type=client_credentials") 
  	http = Net::HTTP.new(uri.host, uri.port)
  	http.use_ssl = true
    req = Net::HTTP::Post.new(uri, {'Authorization' => "Basic MGU5OWIwMGY5MDc1NDE4OTg4ZTgyOTM2YjE3ZmY5YmY6U2hzMnhVNW9tc1B6M2xmTEd0a2lxNHhta3ZqU2JTZmtCV1Nwd2NHVHh2UGF2Mmx6ZUFQQ1l4ZDZ1OXROdFVhZw=="})
    res = http.request(req)
	result = JSON.parse(res.body) if res.code == "200"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
    skip_before_action :verify_authenticity_token

    include Response
    include Allegro
    include DeviseTokenAuth::Concerns::SetUserByToken
end

app/controllers/barcode_no_logins_controller.rb
class BarcodeNoLoginsController < ApplicationController
  # POST /barcode_no_logins
  # POST /barcode_no_logins.json
  def create
    @barcode_no_login = BarcodeNoLogin.new(barcode_no_login_params)

    respond_to do |format|
      if @barcode_no_login.save
        FindResultsJob.perform_later @barcode_no_login

        format.html { redirect_to @barcode_no_login, notice: 'Barcode no login was successfully created.' }
        format.json { json_response(@barcode_no_login) }
      else
        format.html { render :new }
        format.json { render json: @barcode_no_login.errors, status: :unprocessable_entity }
      end
    end
  end

  
  private  
    def barcode_no_login_params
      params.permit(:code)
    end
end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController
  before_action :set_barcode, only: [:destroy]
  # before_action :authenticate_user!

  require "uri"
  require "net/http"

  def index
    email = request.headers["uid"]
    @barcodes = Barcode.where(user: User.where(email: email).first).last
    json_response(@barcodes)
  end

  def new
    @barcode = Barcode.new
  end

  def edit
  end

  def create
    @barcode = Barcode.new(barcode_params)
    email = request.headers["uid"]
    @barcode.update_attributes(user: User.where(email: email).first) if email
    # get_result(params["code"], get_tokens["access-token"], get_tokens["jti"])

    respond_to do |format|
      if @barcode.save
        FindResultsJob.perform_later @barcode
        format.json { json_response(@barcode) }
      else
        format.json { render json: @barcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barcodes/1
  # DELETE /barcodes/1.json
  def destroy
    @barcode.destroy
    respond_to do |format|
      format.html { redirect_to barcodes_url, notice: 'Barcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_barcode
    json_response(params[:upc])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barcode
      @barcode = Barcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barcode_params
      params.permit(:code, :upc)
    end
end

app/controllers/concerns/allegro.rb
module Allegro	
	def get_tokens
		uri = URI.parse("https://allegro.pl/auth/oauth/token?grant_type=client_credentials") 
	  	http = Net::HTTP.new(uri.host, uri.port)
	  	http.use_ssl = true
	    req = Net::HTTP::Post.new(uri, {'Authorization' => "Basic MGU5OWIwMGY5MDc1NDE4OTg4ZTgyOTM2YjE3ZmY5YmY6U2hzMnhVNW9tc1B6M2xmTEd0a2lxNHhta3ZqU2JTZmtCV1Nwd2NHVHh2UGF2Mmx6ZUFQQ1l4ZDZ1OXROdFVhZw=="})
	    res = http.request(req)
		JSON.parse(res.body) if res.code == "200"
	end
end

app/controllers/concerns/response.rb
module Response 
	def json_response(object, status = :ok)
		render json: object, status: status
	end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show]

  def index
    @results = Barcode.find(params[:barcode_id]).results
    json_response(@results)
  end

  def show
    json_response(Result.find(params[:id]))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.permit(:name, :description, :image, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barcode_no_logins_helper.rb
module BarcodeNoLoginsHelper
end

app/helpers/barcodes_helper.rb
module BarcodesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/barcode_no_logins/_form.html.erb
<%= form_with(model: barcode_no_login, local: true) do |form| %>
  <% if barcode_no_login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(barcode_no_login.errors.count, "error") %> prohibited this barcode_no_login from being saved:</h2>

      <ul>
      <% barcode_no_login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/barcode_no_logins/edit.html.erb
<h1>Editing Barcode No Login</h1>

<%= render 'form', barcode_no_login: @barcode_no_login %>

<%= link_to 'Show', @barcode_no_login %> |
<%= link_to 'Back', barcode_no_logins_path %>

app/views/barcode_no_logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Barcode No Logins</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @barcode_no_logins.each do |barcode_no_login| %>
      <tr>
        <td><%= barcode_no_login.code %></td>
        <td><%= link_to 'Show', barcode_no_login %></td>
        <td><%= link_to 'Edit', edit_barcode_no_login_path(barcode_no_login) %></td>
        <td><%= link_to 'Destroy', barcode_no_login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barcode No Login', new_barcode_no_login_path %>

app/views/barcode_no_logins/new.html.erb
<h1>New Barcode No Login</h1>

<%= render 'form', barcode_no_login: @barcode_no_login %>

<%= link_to 'Back', barcode_no_logins_path %>

app/views/barcode_no_logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @barcode_no_login.code %>
</p>

<%= link_to 'Edit', edit_barcode_no_login_path(@barcode_no_login) %> |
<%= link_to 'Back', barcode_no_logins_path %>

app/views/barcodes/scanner.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<div class="container-fluid">
	<div class="jumbotron text-center" id="jumbo">
		<div class="text-center" id='barcode-scanner'></div>
		<h1 class="display-4">Scan time!</h1>
		<p class="lead">Please point you camera at the barcode.</p>
	</div>
</div>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TardisBack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>